### ISSUE TITLE
Custom methods for clicks on context menu items

### ISSUE THREAD

**Issue by ehhc** [mixmaxhq/electron-editor-context-menu#12]
Is it somehow possible to pass custom functions to the context menu that should be executed when a certain item was clicked?
e.g. i need to execute a custom function when the user clicks on a spell suggestion. Can i somehow make your context menu execute my custom function on click?

Thanks a lot :)

**Comment by wearhere** [comment]
The library doesn't yet let spelling suggestions' [handler](https://github.com/mixmaxhq/electron-editor-context-menu/blob/dbb3474f0767304a7fb5a7f50e36c0b34ef1de03/src/index.js#L102) be customized, would accept a PR for that!

For other items, you can override the [main template](https://github.com/mixmaxhq/electron-editor-context-menu/blob/dbb3474f0767304a7fb5a7f50e36c0b34ef1de03/src/index.js#L75).

**Comment by ehhc** [comment]
Hi,
thanks a lot for your reply.
Unfortunately i noticed i need to change some other things as well. So i guess it's easier to create a menu myself (i will orientate myself on your work if thats okay) for my specific use case.
Thansk a lot anyway.
